use anyhow::{Result, Context};
use reqwest::Client;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::time::Duration;

/// Proveedor de LLM
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LlmProvider {
    /// Ollama (https://ollama.ai)
    Ollama,
    /// Directo a la API OpenAI compatible
    OpenAiCompatible,
}

/// Configuración para el cliente LLM
#[derive(Debug, Clone)]
pub struct LlmConfig {
    /// Proveedor seleccionado
    pub provider: LlmProvider,
    /// URL base para la API
    pub api_url: String,
    /// Modelo a utilizar
    pub model: String,
    /// API Key para autenticación (requerida para OpenAI)
    pub api_key: Option<String>,
    /// Temperatura (creatividad) del modelo
    pub temperature: f32,
    /// Timeout en segundos
    pub timeout_seconds: u64,
    /// Longitud máxima de salida
    pub max_tokens: Option<u32>,
}

impl Default for LlmConfig {
    fn default() -> Self {
        Self {
            provider: LlmProvider::Ollama,
            api_url: "http://localhost:11434/api".to_string(),
            model: "llama2".to_string(),
            api_key: None,
            temperature: 0.5,
            timeout_seconds: 30,
            max_tokens: Some(512),
        }
    }
}

/// Solicitud a Ollama
#[derive(Debug, Serialize)]
struct OllamaRequest {
    model: String,
    prompt: String,
    temperature: f32,
    #[serde(skip_serializing_if = "Option::is_none")]
    max_tokens: Option<u32>,
}

/// Respuesta de Ollama u OpenAI
#[derive(Debug, Deserialize)]
struct OllamaResponse {
    #[serde(default)]
    model: String,
    #[serde(default)]
    response: String,
    #[serde(default)]
    choices: Vec<Choice>,
}

#[derive(Debug, Deserialize)]
struct Choice {
    message: Option<Message>,
    #[serde(default)]
    index: i32,
}

#[derive(Debug, Deserialize)]
struct Message {
    content: String,
}

/// Cliente para interactuar con el LLM
pub struct LlmClient {
    config: LlmConfig,
    client: Client,
}

impl LlmClient {
    /// Crear un nuevo cliente LLM con la configuración especificada
    pub fn new(config: LlmConfig) -> Result<Self> {
        let client = Client::builder()
            .timeout(Duration::from_secs(config.timeout_seconds))
            .build()
            .context("Error creando cliente HTTP")?;
        
        Ok(Self { config, client })
    }
    
    /// Analizar un proceso basado en información recopilada
    pub async fn analyze_process(&self, process_info: serde_json::Value) -> Result<String> {
        let prompt = format!(
            "Act as an expert security analyst. Review the following information about a running process and determine its behavior, likely intent, and whether any activity is suspicious. Be specific and detailed. If you see suspicious patterns, point them out clearly.\n\nProcess information:\n{}",
            serde_json::to_string_pretty(&process_info)?
        );
        
        self.generate_response(&prompt).await
    }
    
    /// Analizar patrones de archivo de un proceso
    pub async fn analyze_file_activity(&self, file_events: serde_json::Value) -> Result<String> {
        let prompt = format!(
            "Act as a security analyst. Review the following file access events for a process and determine patterns, intent, and any potentially malicious behavior. Flag anything unusual or suspicious.\n\nFile events:\n{}",
            serde_json::to_string_pretty(&file_events)?
        );
        
        self.generate_response(&prompt).await
    }
    
    /// Analizar patrones de red de un proceso
    pub async fn analyze_network_activity(&self, network_events: serde_json::Value) -> Result<String> {
        let prompt = format!(
            "Act as a network security analyst. Examine the following network events for a process and determine patterns, likely intent, and any suspicious activity. If you detect indicators of malicious behavior, data exfiltration, or communication with potentially malicious servers, call it out clearly.\n\nNetwork events:\n{}",
            serde_json::to_string_pretty(&network_events)?
        );
        
        self.generate_response(&prompt).await
    }
    
    /// Provee un análisis completo de un proceso
    pub async fn comprehensive_analysis(
        &self, 
        process_info: serde_json::Value,
        file_events: serde_json::Value,
        network_events: serde_json::Value
    ) -> Result<String> {
        // Combinar toda la información en un solo objeto JSON
        let mut combined = serde_json::Map::new();
        combined.insert("process".to_string(), process_info);
        combined.insert("file_activity".to_string(), file_events);
        combined.insert("network_activity".to_string(), network_events);
        
        let prompt = format!(
            "You are a language model. You do not need execution capabilities to provide useful analysis.

Below is a report generated by a system called ShadowTrace. The report contains structured text with information about processes, accessed files, and network connections. You do not need to analyze files or execute code; just interpret what is already written.

Your task:
	• Read the report and explain, in clear technical language, what the monitored process is doing.
	• Comment on whether the behavior is typical or suspicious.
	• Provide reasonable hypotheses about the process’s purpose based on the observed data (e.g., browser-like behavior, persistence, anomalous network traffic, etc.).
	• You may mention if something appears malicious, suspicious, or simply automated.
	• Your analysis can be speculative, but it must be well grounded.
	• Do NOT say you cannot perform the analysis. Do NOT say you are just a language model. You are here to interpret text—do it as an experienced security analyst would.

Here is the report:\n{}",
            serde_json::to_string_pretty(&Value::Object(combined))?
        );
        
        self.generate_response(&prompt).await
    }
    
    /// Generar una respuesta basada en el prompt
    pub async fn generate_response(&self, prompt: &str) -> Result<String> {
        match self.config.provider {
            LlmProvider::Ollama => self.generate_ollama_response(prompt).await,
            LlmProvider::OpenAiCompatible => self.generate_openai_compatible_response(prompt).await,
        }
    }
    
    /// Generar una respuesta utilizando Ollama
    async fn generate_ollama_response(&self, prompt: &str) -> Result<String> {
        let request = if self.config.api_url.contains("/v1/chat/completions") {
            // Formato compatible con OpenAI
            let openai_request = serde_json::json!({
                "model": self.config.model.clone(),
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a cybersecurity assistant with deep knowledge of process behavior analysis and threat detection. ALWAYS respond in English. If the input is in another language (e.g., Spanish), translate it and respond in English using appropriate technical terminology."
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                "temperature": self.config.temperature,
                "max_tokens": self.config.max_tokens,
            });
            openai_request
        } else {
            // Formato de Ollama
            let ollama_request = OllamaRequest {
                model: self.config.model.clone(),
                prompt: format!("{}\n\n{}","ALWAYS respond in English. If the input is in another language (e.g., Spanish), translate it and respond in English using appropriate technical terminology.", prompt),
                temperature: self.config.temperature,
                max_tokens: self.config.max_tokens,
            };
            serde_json::to_value(ollama_request)?
        };
        
        // Determinar la URL correcta: si ya contiene un endpoint específico, usarla directamente
        let url = if self.config.api_url.contains("/v1/chat/completions") 
                  || self.config.api_url.contains("/generate") {
            self.config.api_url.clone()
        } else {
            format!("{}/generate", self.config.api_url)
        };
        
        let response = self.client.post(&url)
            .json(&request)
            .send()
            .await?
            .json::<OllamaResponse>()
            .await?;
            
        // Obtener la respuesta del formato correcto
        if !response.response.is_empty() {
            // Es una respuesta de Ollama
            Ok(response.response)
        } else if !response.choices.is_empty() && response.choices[0].message.is_some() {
            // Es una respuesta de OpenAI
            Ok(response.choices[0].message.as_ref().unwrap().content.clone())
        } else {
            Err(anyhow::anyhow!("No se pudo obtener respuesta del LLM"))
        }
    }
    
    /// Generar una respuesta utilizando una API compatible con OpenAI
    async fn generate_openai_compatible_response(&self, prompt: &str) -> Result<String> {
        // Validar que el modelo esté configurado
        if self.config.model.is_empty() {
            return Err(anyhow::anyhow!("Model cannot be empty. Please configure a valid model (e.g., gpt-4o-mini)"));
        }
        
        // Estructura para API compatible con OpenAI
        #[derive(Serialize)]
        struct OpenAiRequest {
            model: String,
            messages: Vec<Message>,
            temperature: f32,
            #[serde(skip_serializing_if = "Option::is_none")]
            max_tokens: Option<u32>,
        }
        
        #[derive(Serialize)]
        struct Message {
            role: String,
            content: String,
        }
        
        let request = OpenAiRequest {
            model: self.config.model.clone(),
            messages: vec![
                Message {
                    role: "system".to_string(),
                    content: "You are a cybersecurity assistant with deep knowledge of process behavior analysis and threat detection. ALWAYS respond in English. If the input is in another language (e.g., Spanish), translate it and respond in English using appropriate technical terminology.".to_string(),
                },
                Message {
                    role: "user".to_string(),
                    content: prompt.to_string(),
                },
            ],
            temperature: self.config.temperature,
            max_tokens: self.config.max_tokens,
        };
        
        // Construir la solicitud HTTP con reqwest
        // Usar .json() que automáticamente serializa y establece Content-Type: application/json
        let mut req = self.client.post(&self.config.api_url)
            .json(&request);
        
        // Agregar header de autenticación si hay API key
        if let Some(api_key) = &self.config.api_key {
            req = req.header("Authorization", format!("Bearer {}", api_key));
        }
        
        let response = req
            .send()
            .await
            .context("Error al enviar solicitud a OpenAI API")?;
        
        // Verificar el código de estado HTTP
        let status = response.status();
        if !status.is_success() {
            let error_text = response.text().await.unwrap_or_else(|_| "Error desconocido".to_string());
            return Err(anyhow::anyhow!(
                "Error HTTP {}: {}",
                status.as_u16(),
                error_text
            ));
        }
        
        let response_json: Value = response
            .json()
            .await
            .context("Error al parsear respuesta JSON de OpenAI")?;
        
        // Extraer el texto de la respuesta (estructura estándar de OpenAI API)
        let content = response_json["choices"][0]["message"]["content"]
            .as_str()
            .context("No se pudo extraer el contenido de la respuesta. Verifica que la respuesta tenga el formato esperado.")?;
            
        Ok(content.to_string())
    }
} 
